### ISSUE TITLE
Adding 5.4.0 support

### ISSUE THREAD

**Issue by mariogamer2** [wiiudev/libwiiu#40]
A lot of poeple are on 5.4.0 and waiting for official kernel support and other app....

**Comment by TheRMario** [comment]
I think the kernel its already out for 5.4 ? Because 5.4 has more content than 5.5.0, also 5.4 can run Loadiine  and 5.5 can't run Loadiine at this moment

**Comment by mariogamer2** [comment]
Yeah but not officially in the libwiiu (source)

**Comment by CreeperMario** [comment]
I'm pretty sure the kernel exploit for 5.4.0 is exactly the same as the one in 5.3.2, hence homebrew built for 5.3.2 should also work on 5.4.0. I could be wrong, and I can't test this myself. (I was late to the homebrew scene, my Wii U is running 5.5.1 with Tubehax DNS)

Although, I have heard about people on GBATemp having trouble running homebrew games by @SonyUSA @eliboa @VGMoose and brienj on 5.4 - can any of you give some insight on 5.4.0 compatibility?

**Comment by TheRMario** [comment]
Adding 5.5.0 support

**Comment by CreeperMario** [comment]
5.5.0 support is already in libwiiu ( thanks to @TheJosamilu ), and I would know, I'm currently using it. 😜
But no **public** kernel exploit for 5.5.0 yet, there are at least three private exploits, all ready to be released once one of them gets patched.

**Comment by TheRMario** [comment]
This are the best, I think :D
5.3.2 ☑ Excellent 
5.4.0 ☑ Awesome
5.5.0 ☑ Good
5.1.1 ☑ Nice

ⓒⓡⓔⓔⓟⓔⓡ  ⓜⓐⓡⓘⓞ

**Comment by vgmoose** [comment]
I have no first hand experience to provide, as I'm also on 5.5.1. However, as far as I know, 5.4.0 should be the same as 5.3.2 in terms of compatibility.

**Comment by Hayajiro** [comment]
Regarding compatibility of Kernel Exploits:
5.3.2 == 5.4.0
5.5.0 == 5.5.1

So if you're on 5.5.0, you can update to 5.5.1

**Comment by mariogamer2** [comment]
@Ciapa1 I'm on 5.5.0, I don't know if I update for the webkit exploit...

**Comment by TheRMario** [comment]
I think 5.5.0 is more save than 5.5.1

**Comment by CreeperMario** [comment]
The only difference between 5.5.0 and 5.5.1 is literally the web browser, all Nintendo did is patch two possible exploits, but left the one by @yellows8 untouched. They also didn't youch the kernel or IOSU programs, so no differences there either. For homebrew developers, there's virtually no difference between 5.5.0 and 5.5.1, so you may as well just update to 5.5.1 while you still can (assuming Nintendo will bring out a 5.5.2, 5.6.0 or 6.0.0 update) and enjoy being able to access the eShop, game updates and online play (due to game updates). I've done that, and am enjoying Course World in Super Mario Maker to the best of my ability.

If you're on 5.3.2 or 5.4.0, you can either choose to stay where you are and enjoy save editing, game mods and backups, or you can update to 5.5.1 and enjoy the community's latest homebrew games and apps (as most new devs are choosing to develop against 5.5).

**Comment by CreeperMario** [comment]
Has this issue been solved? I may still be able to provide assistance.

**Comment by mariogamer2** [comment]
Yeah as you say it's the same exploit sorry for taking to long
